apps/bioseq/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('<int:obj_id>/import/', views.import_seq_file, name='import_seq_file'),
    path('<int:obj_id>/sequence/<int:seq_id>/', views.display, name='display_sequence'),
    path('<int:obj_id>/sequence/<int:seq_id>/edit/', views.edit_sequence, name='edit_sequence'),
    path('<int:obj_id>/delete/<int:seq_id>/', views.delete_sequence, name='delete_sequence'),
    re_path(r'^(?P<obj_id>\d+)/blast/(?P<seq_id>\d+)/(?P<mode>(local|www))/$', views.blast_sequence, name='blast_sequence'),
    path('<int:obj_id>/blast/<int:blast_id>/display/', views.blast_display, name='blast_display'),
]

common/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.utils import timezone
from django.views.decorators.http import last_modified
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from invent.forms import ImageSearchForm
from invent import views
from proj import views as proj_views
from policy import views as pol_views
from publications import views as publications_views

handler500 = 'proj.views.server_error'
last_modified_date = timezone.now()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taxo/',  include('apps.taxo.urls')),
    path('seq/', include('bioseq.urls')),
    path('tinymce/', include('tinymce.urls')),

    #path('register/', proj_views.site_register, name='register'),
    #path('register/success/', TemplateView.as_view(template_name='proj/register_success.html'), name='register_success'),
    #path('register/activate/<key>/', proj_views.activate_account, name='register_activation'),
    path('login/', auth_views.LoginView.as_view(template_name='proj/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/profile/', proj_views.profile, name='profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    re_path(r'^setlang/(?P<lang>(fr|en))/$', proj_views.set_language, name='setlang'),
    path('site_admin/', proj_views.site_admin, name='site_admin'),
    path('help/', proj_views.help_index, name='help_index'),
    path('help/<subject>/', proj_views.help, name='help'),

    path('jsi18n/', last_modified(lambda req, **kw: last_modified_date)(JavaScriptCatalog.as_view()),
        name='javascript_catalog'),

    path('policy/', pol_views.accept_policy, name='accept_policy'),
    path('', views.IndexView.as_view(), name='home'),

    path('search/', views.SearchView.as_view(), name='search'),
    path('search/export', views.SearchView.as_view(output='export'), name='search-export'),
    path('search/export-options', views.SearchView.as_view(output='export-options'), name='search-export-options'),
    path('search/add_criterion/<int:base_num>/',
        views.add_criterion, name='add_criterion'),
    path('search_images/', views.SearchView.as_view(form_class=ImageSearchForm, template_name='search/search_images.html'),
        name='search_img'),

    path('invent/', views.invent_list, name='inventories'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('invent/<int:parent_id>/new/<obj_code>/', views.ObjectCreateView.as_view(), name='object_create'),
    path('invent/<int:obj_id>/', views.object_detail, name='object_detail'),
    path('invent/<int:obj_id>/as_image/', views.object_image, name='object_image'),
    path('invent/<int:obj_id>/edit/', views.ObjectEditView.as_view(), name='object_edit'),
    path('invent/<int:obj_id>/editperms/', views.object_edit_perms, name='object_edit_perms'),
    path('invent/<int:obj_id>/delete/', views.object_delete, name='object_delete'),
    re_path(r'^invent/(?P<obj_id>\d+)/contents/(?P<otype>[-\w]+)?/?$',
        views.PaginatedObjectsView.as_view(), name='object_list'),
    path('invent/<int:obj_id>/reverse_refs/',
        views.PaginatedReverseObjectsView.as_view(), name='reverse_objects'),
    re_path(r'^invent/(?P<obj_id>\d+)/contents/(?P<otype>[-\w]+)/(?P<format>(table|geojson))/$',
        views.object_list_table, name='object_list_table'),
    re_path(r'^invent/by_uuid/(?P<uuid>[-\w]+)/(?P<format>(html|json|xml))?/?$',
        views.object_list_by_uuid, name='object_by_uuid'),
    path('invent/<int:obj_id>/import/', views.object_import, name='object_import'),
    path('attributes/', views.attributes, name='attributes'),
    # attribute name passed in GET
    path('attributes/vocab/', views.vocab_for_attribute, name='vocab_for_attribute'),

    re_path(r'^attributes_in_group/(?P<group_id>-?\d+)/$', views.attributes_in_group),

    path('<int:object_id>/value/new/<int:attr_id>/', views.add_value, name='add_value'),
    re_path(r'^(?P<object_id>\d+)/value/(?P<value_id>[\w\-]+)/edit/$', views.edit_value),
    path('<int:object_id>/value/del/', views.del_value, name='del_value'), # value id in POST
    # Image and file attachment editing
    path('<int:object_id>/photo/add/', views.add_photo, name="add_photo"),
    path('<int:object_id>/photo/<int:photo_id>/edit/', views.edit_photo),
    path('<int:object_id>/photo/del/', views.del_photo), # photo id in POST
    path('<int:object_id>/file/<int:file_id>/edit/', views.edit_file, name='edit_file'),
    path('<int:object_id>/file/del/', views.del_file), # file id in POST

    path('publications/', publications_views.PublicationsView.as_view(), name='publications'),
    path('press-corner/', publications_views.PressCornerView.as_view(), name='press_corner'),
]

if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

apps/bioseq/forms.py
# Copyright (c) 2010,2016 Claude Paroz <claude@2xlibre.net>

from django import forms
from django.utils.translation import gettext_lazy as _

from bioseq.utils import guess_format, UnsupportedFileFormat
from .models import BioEntry


class ImportForm(forms.Form):
    seqfile = forms.FileField(label = _("File containing sequence(s)"), required=False)
    ncbi_accession = forms.CharField(label = _("NCBI accession number"), required=False)
    target = forms.ChoiceField(
        choices=(
            ('current', _("Attach all sequences to the current accession")),
            ('any', _("Map the sequence identifier with any accession number in the collection"))
        ), initial='current', widget=forms.RadioSelect)

    def clean(self):
        if not self.cleaned_data.get('seqfile') and not self.cleaned_data.get('ncbi_accession'):
            raise forms.ValidationError(_("Please provide either a file or a NCBI accession number"))
        return self.cleaned_data

    def clean_seqfile(self):
        seqf = self.cleaned_data['seqfile']
        if seqf:
            try:
                self.format = guess_format(seqf)
            except UnsupportedFileFormat:
                raise forms.ValidationError(_("Sorry, the file you provided has not been recognized as a sequence file format"))
        return seqf


class BioEntryForm(forms.ModelForm):
    class Meta:
        model = BioEntry
        fields = [
            "name", "accession", "identifier", "unite_number", "division", "description", "version"
        ]

apps/bioseq/views.py
# Copyright (c) 2010 Claude Paroz <claude@2xlibre.net>

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_save
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST

from invent.models import BaseObject
from invent.views import permission_denied
from . import models
from .forms import BioEntryForm, ImportForm
from .utils import import_sequence, make_blast_db


def import_seq_file(request, obj_id):
    """ Import a sequence file """
    obj = get_object_or_404(BaseObject, pk=obj_id)
    if not obj.can_edit(request.user):
        return HttpResponseForbidden(_("You are not allowed to edit this object"))
    import_form = ImportForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if import_form.is_valid():
            seqfile = import_form.cleaned_data.get('seqfile', None)
            acc_num = import_form.cleaned_data.get('ncbi_accession', None)
            target = import_form.cleaned_data['target']
            bioentries = []
            # Disconnecting signal so make_blast_db runs only at the end of all imports
            post_save.disconnect(models.update_blast_db, sender=models.BioSequence)
            try:
                bioentries = import_sequence(obj, seqfile, acc_num, target=target)
            except Exception as e:
                messages.error(request, str(e))
            else:
                messages.success(request, "%d sequences have been updated." % len(bioentries))
                if len(bioentries) == 1:
                    return HttpResponseRedirect(reverse('display_sequence', args=[obj.pk, bioentries[0].pk]))
                else:
                    return HttpResponseRedirect(reverse('object_detail', args=[obj.pk]))
            finally:
                post_save.connect(models.update_blast_db, sender=models.BioSequence)
                if len(bioentries) > 0:
                    make_blast_db()
    context = {
        'obj'   : obj,
        'form'  : import_form,
    }
    return render(request, 'bioseq/import.html', context)


def display(request, obj_id, seq_id):
    """ Display a sequence """
    obj = get_object_or_404(BaseObject, pk=obj_id)
    bioentry = get_object_or_404(models.BioEntry, pk=seq_id)
    format = request.GET.get('format', 'html')
    if not obj.can_view(request.user):
        return permission_denied(request)
    breadcrumb = obj.breadcrumb(link_self=True)
    breadcrumb.append((_("Molecular sequence"), ""))
    context = {
        'obj'     : obj,
        'breadcrumb' : breadcrumb,
        'editable': obj.can_edit(request.user),
        'bioentry': bioentry,
    }
    if format == 'html':
        template = 'bioseq/display.html'
        context['sequence'] = bioentry.get_sequence()
        context['features'] = bioentry.seqfeature_set.all().order_by('rank')
    else:
        if format == 'genbank' and bioentry.biosequence.alphabet == 'unknown':
            context['raw'] = """Sorry, not enough information for this sequence to be displayed in GenBank format"""
        else:
            context['raw'] = bioentry.format(format)
        template = 'bioseq/display-formatted.html'
    return render(request, template, context)


def edit_sequence(request, obj_id, seq_id):
    obj = get_object_or_404(BaseObject, pk=obj_id)
    bioentry = get_object_or_404(models.BioEntry, pk=seq_id)
    if request.method == 'POST':
        form = BioEntryForm(instance=bioentry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("display_sequence", args=[obj.pk, bioentry.pk]))
    else:
        form = BioEntryForm(instance=bioentry)
    context = {
        'object': obj,
        'form': form,
    }
    return render(request, 'bioseq/bioentry_edit.html', context)


@require_POST
def delete_sequence(request, obj_id, seq_id):
    """ Delete a sequence """
    # Get sequence, check rights, delete, redirect to object details
    obj = get_object_or_404(BaseObject, pk=obj_id)
    bioentry = get_object_or_404(models.BioEntry, pk=seq_id)
    if not obj.can_edit(request.user):
        return HttpResponseForbidden(_("You are not allowed to edit this object"))
    if bioentry.baseobjects.count() > 1:
        bioentry.baseobjects.remove(obj)
    else:
        bioentry.delete()
    return HttpResponseRedirect(reverse('object_detail', args=[obj.pk]))

@login_required
def blast_sequence(request, obj_id, seq_id, mode):
    """ Run a local blast with sequence data """
    obj = get_object_or_404(BaseObject, pk=obj_id)
    bioentry = get_object_or_404(models.BioEntry, pk=seq_id)
    blast = bioentry.biosequence.blastn(request.user, mode)
    return HttpResponseRedirect(reverse('blast_display', args=[obj.pk, blast.pk]))

def blast_display(request, obj_id, blast_id):
    """ Display a specific blast result """
    obj = get_object_or_404(BaseObject, pk=obj_id)
    blast = get_object_or_404(models.BlastResult, pk=blast_id)
    record = blast.read()
    breadcrumb = obj.breadcrumb(link_self=True)
    breadcrumb.append((blast.bioentry.name, reverse("display_sequence", args=[obj.pk, blast.bioentry.pk])))
    breadcrumb.append((_("Blast result"), ""))
    context = {
        'obj'   : obj,
        'breadcrumb' : breadcrumb,
        'blast' : blast,
        'record': record,
    }
    return render(request, 'bioseq/blast_result.html', context)

templates/bioseq/attribute_render.html
{# called from invent/object_detail to render a bioseq element #}
<div><a href="{% url 'display_sequence' obj.id attr_values.pk %}"><img src="{% static 'icons/dna-gr.png' %}"/> {{ attr_title }}</a></div>

templates/bioseq/bioentry_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Sequence editing"%}{% endblock %}

{% block content %}

<form name="edit_form" method="post" class="form" action=".">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <table>
    {{ form.as_table }}
    </table>
    <button type="submit">{% trans 'Save' %}</button>
</form>

{% endblock content %}

templates/bioseq/blast_result.html
{% extends "base.html" %}
{% load i18n bioseq %}
{% block title %}{% trans "Blast result"%}{% endblock %}

{% block extra_head %}
<script type="text/javascript">
$(document).ready(function() {
  $(".expander").toggle(function() {
      $(".expandable_content", $(this).parent().parent()).hide();
      $(this).attr("src", "{% static 'img/closed.png' %}");
    }, function() {
      $(".expandable_content", $(this).parent().parent()).show();
      $(this).attr("src", "{% static 'img/open.png' %}");
    });
});
</script>
{% endblock %}

{% block content %}
<h1>{{ obj.title }}</h1>
{% trans "Program used:" %} {{ record.application }} ({{ record.version }})<br/>
{% trans "Database:" %} {{ record.database }} ({% if blast.is_local %}local{% else %}online{% endif %})<br/>
{% trans "Date:" %} {{ blast.blast_date|date:"Y-m-d H:i" }}<br/>
{% for align in record.alignments %}
  <div class="alignment" style="border: 1px dotted gray; padding: 2px; margin-top:0.5em;">{{ forloop.counter }}. {{ align.hit_def }}<br/>
  {% for hsp in align.hsps %}
    {% trans "Score:" %} {{ hsp.score }}<br/>
    {% trans "Identities:" %} {{ hsp.identities }}/{{ hsp.align_length }} ({{ hsp|ident_perc }}%)<br />
  
    <div class="expandable"><a href="."><img src="{% static 'img/open.png' %}" class="expander"></a>{% trans "Alignment:" %}
      <div class="expandable_content">{{ hsp|split_align:"75" }}</div>
    </div>
  {% endfor %}
  </div>
{% empty %}
  {% trans "No hit" %}
{% endfor %}

{% endblock %}

templates/bioseq/display-formatted.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Sequence display"%}{% endblock %}

{% block content %}

{% if editable %}
<div class="edit_icons">
  <form method="post" action="{% url 'delete_sequence' obj.pk bioentry.pk %}" onsubmit="return confirm('{% trans "Do you really want to delete this sequence?" %}');" style="display: inline">
    {% csrf_token %}
    <input type="image" src="{% static 'img/delete.png' %}" alt="delete icon" title="{% trans "Delete" %}" width="16" /></form>
</div>
{% endif %}

<h1>{{ obj.title }}</h1>

<div><pre>{{ raw }}</pre></div>

<div align="right" style="font-size:90%">Format:  <a href=".">HTML</a> | <a href=".?format=genbank">GenBank</a> | <a href=".?format=fasta">FASTA</a></div>
{% endblock %}

templates/bioseq/display.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Sequence display"%}{% endblock %}

{% block extra_head %}
<script type="text/javascript">
var previous_content = new Array();

function hilite(start_idx, end_idx) {
  /* Hilite some part of a sequence string */
  var stline_no = Math.floor((start_idx-1)/60);
  var stchar_no = ((start_idx-1)%60);
  stchar_no += Math.floor(stchar_no/10) // spaces
  var enline_no = Math.floor((end_idx-1)/60);
  var enchar_no = ((end_idx-1)%60) +1;
  enchar_no += Math.floor(enchar_no/10) // spaces
  /* Save original content */
  for (idx=stline_no; idx <= enline_no; idx++) {
    previous_content[idx] = $("#line-"+ idx).html();
  }
  /* begin by end span */
  var enline_cont = $("#line-"+ enline_no).html();
  enline_cont = enline_cont.substr(0,enchar_no) + "</span>" + enline_cont.substr(enchar_no)
  if (enline_no == stline_no) {
    enline_cont = enline_cont.substr(0,stchar_no) + "<span style='background-color:#ff0;'>" + enline_cont.substr(stchar_no);
    $("#line-"+ enline_no).html(enline_cont);
  } else {
    enline_cont = "<span style='background-color:#ff0;'>" + enline_cont;
    $("#line-"+ enline_no).html(enline_cont);
    /* mark all lines until begin */
    for (idx=stline_no; idx<enline_no; idx++) {
      var line_cont = $("#line-"+ idx).html();
      if (idx==stline_no) {
        line_cont = line_cont.substr(0,stchar_no) + "<span style='background-color:#ff0;'>" + line_cont.substr(stchar_no);
      } else {
        line_cont = "<span style='background-color:#ff0;'>" + line_cont;
      }
      line_cont = line_cont + "</span>";
      $("#line-"+ idx).html(line_cont);
    }
  }
  $("#line-"+ enline_no).html(enline_cont);
}

function unhilite(start_idx, end_idx) {
  var stline_no = Math.floor((start_idx-1)/60);
  var enline_no = Math.floor((end_idx-1)/60);
  for (idx=stline_no; idx <= enline_no; idx++) {
    $("#line-"+ idx).html(previous_content[idx]);
  }
  previous_content.length=0;
}

$(document).ready(function() {
    $(".location").hover(function() {
        var splitted_id = $(this).attr('id').split('-');
        hilite(splitted_id[2], splitted_id[3]);
        $(this).css({'background-color': '#ff0'});
    }, function() {
        var splitted_id = $(this).attr('id').split('-');
        unhilite(splitted_id[2], splitted_id[3]);
        $(this).css({'background-color': '#fff'});
    });
});
</script>
{% endblock %}

{% block content %}

{% if editable %}
<div class="edit_icons">
    <a class="icon" href="{% url 'edit_sequence' obj.pk bioentry.pk %}">
        <img src="{% static 'img/edit.png' %}" alt="edit icon" title="{% trans "Edit sequence" %}" width="18">
    </a>

  <form method="post" action="{% url 'delete_sequence' obj.pk bioentry.pk %}" onsubmit="return confirm('{% trans "Do you really want to delete this sequence?" %}');" style="display: inline">
    {% csrf_token %}
    <input type="image" src="{% static 'img/delete.png' %}" alt="delete icon" title="{% trans "Delete" %}" width="16" /></form>
</div>
{% endif %}

<h1>{{ obj.title }}</h1>
<table border="0">
<tr><th class="left_header">{% trans "Name" %}</th><td>{{ bioentry.name }}</td>
                            <th class="left_header">{% if bioentry.division %}<strong>{% trans "Division" %}</strong></th>
                            <td>{{ bioentry.division }} <a href="http://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html#GenBankDivisionB" class="icon"><img src="{% static 'icons/help.png' %}" title="{% trans 'What is this?' %}"/></a>{% else %}</th><td>{% endif %}</td></tr>
<tr><th class="left_header">{% trans "Accession" %}</th><td>{{ bioentry.accession }}</td>
                            <th class="left_header">{% if bioentry.version %}<strong>{% trans "Version" %}</strong></th>
                            <td>{{ bioentry.version }}{% else %}</th><td>{% endif %}</td></tr>
<tr><th class="left_header">{% trans "Identifier" %}</th><td>{{ bioentry.identifier }}</td></tr>
<tr><th class="left_header">{% trans "Description" %}</th><td colspan="3">{{ bioentry.description }}</td></tr>
{% if bioentry.unite_number %}
<tr><th class="left_header">{% trans "Unite number" %}</th>
    <td colspan="3"><a href="https://unite.ut.ee/sh/{{ bioentry.unite_number }}" target="_blank">{{ bioentry.unite_number }}</a></td>
</tr>
{% endif %}
{% if bioentry.keywords %}
<tr><th class="left_header">{% trans "Keywords" %}</th><td colspan="3">{{ bioentry.keywords }}</td></tr>
{% endif %}
{% if bioentry.source %}
<tr><th class="left_header">{% trans "Source" %}</th>
    <td colspan="3">{{ bioentry.source }}{% if bioentry.organism %}<br/>
                    <b>{% trans "Organism" %}</b><br/>{{ bioentry.organism }}<br/>{{ bioentry.taxonomy }}{% endif %}</td>
</tr>
{% endif %}
<!-- References -->
{% if bioentry.bioentryreference_set.count %}
<tr><th class="left_header">{% trans "References" %}</th><td colspan="3">
    {% for bref in bioentry.bioentryreference_set.all %}
        <div style="margin-bottom:0.5em;">{{ bref.rank }}{% if bref.start_pos %} (bases {{ bref.start_pos }} to {{ bref.end_pos }}){% endif %}<br/>
        <b>{% trans "Authors" %}</b> {{ bref.reference.authors }}<br/>
        <b>{% trans "Title" %}</b> {{ bref.reference.title }}<br/>
        <b>{% trans "Published in" %}</b> {{ bref.reference.location }}</div>
    {% endfor %}
</td></tr>
{% endif %}
<!-- Features -->
{% for feature in features %}
  {% if forloop.first %}<tr><th class="left_header">{% trans "Features" %}</th><td colspan="3"><table>{% endif %}
  <tr><td valign="top">{{ feature.type_term }}</td>
      <td><div class="location" id="loc-{{ feature.location.id }}-{{ feature.location.start }}-{{ feature.location.end }}">
            <div>{{ feature.location.start }}..{{ feature.location.end }} ({{feature.location.id}})</div>
            {% for qual in feature.qualifiers %}<div>{{ qual.term }} = {{ qual.value }}</div>{% endfor %}
          </div>
      </td>
  </tr>
  {% if forloop.last %}</table></td></tr>{% endif %}
{% endfor %}
</table>
<div align="right"><em>{% trans "Last modified:"%} {{ bioentry.last_modif_date }}</em></div>
<strong>{% blocktrans with sequence|length as length %}Sequence ITS4 ({{ length }} bp):{% endblocktrans %}</strong><br/>
{% for idx,line in bioentry.formatted_sequence %}
  <span style="font-family:monospace; color:#AAAAAA;"><pre style="display:inline;margin-right:1em;">{{ idx }}</pre></span>
  <span style="font-family:monospace;" id="line-{{ forloop.counter0 }}">{% for group in line %}{{ group|safe }} {% endfor %}</span><br/>
{% endfor %}

<div align="right" style="font-size:90%">Format: HTML | <a href=".?format=genbank">GenBank</a> | <a href=".?format=fasta">FASTA</a></div>

{% if user.is_authenticated %}
  <hr/><div>
  {% for blast in bioentry.blastresult_set.all %}
    {% if forloop.first %}<ul>{% endif %}
    <li><a href="{% url 'blast_display' obj.pk blast.pk %}">blasted on {{ blast.blast_date|date:"d.m.Y, H:i" }}</a> by {{ blast.blast_who }}</li>
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}
  <form method="get" action="{% url 'blast_sequence' obj.pk bioentry.pk 'local' %}">
      {% csrf_token %}<input type="submit" value="Run local BLAST">
  </form>
  <form method="get" action="{% url 'blast_sequence' obj.pk bioentry.pk 'www' %}">
      {% csrf_token %}<input type="submit" value="Run online BLAST (nt database)">
  </form>
  </div>
{% endif %}
{% endblock %}

templates/bioseq/import.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Sequence import"%}{% endblock %}

{% block extra_head %}
<style>
ul#id_target { padding: 0; list-style-type: none; }
</style>
{% endblock %}

{% block content %}

<h1>{{ obj.title }}</h1>
<h2>{% trans "Import sequence(s)" %}</h2>
{{ form.non_field_errors }}
<form enctype="multipart/form-data" method="post" action=".">
    {% csrf_token %}
<table class="form">
  <tr><th>{{ form.seqfile.label }}:</th>
      <td>{{ form.seqfile.errors }}{{ form.seqfile }}</td></tr>
  <tr><td></td>
      <td>{{ form.target }}</td></tr>

  <tr><th>{% trans "Or" %}</th></tr>

  <tr><th>{{ form.ncbi_accession.label }}:</th><td>{{ form.ncbi_accession.errors }}{{ form.ncbi_accession }}</td></tr>
  <tr><td colspan="2" align="right">
    <input type="button" onclick="window.location='{{ obj.get_absolute_url }}'" value="{% trans 'Cancel' %}" style="margin-right:2em;">
    <input type="submit" value="{% trans 'Import' %}">
  </td></tr>
</table>
</form>

{% endblock %}