common/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.utils import timezone
from django.views.decorators.http import last_modified
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from invent.forms import ImageSearchForm
from invent import views
from proj import views as proj_views
from policy import views as pol_views
from publications import views as publications_views

handler500 = 'proj.views.server_error'
last_modified_date = timezone.now()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taxo/',  include('apps.taxo.urls')),
    path('seq/', include('bioseq.urls')),
    path('tinymce/', include('tinymce.urls')),

    #path('register/', proj_views.site_register, name='register'),
    #path('register/success/', TemplateView.as_view(template_name='proj/register_success.html'), name='register_success'),
    #path('register/activate/<key>/', proj_views.activate_account, name='register_activation'),
    path('login/', auth_views.LoginView.as_view(template_name='proj/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/profile/', proj_views.profile, name='profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    re_path(r'^setlang/(?P<lang>(fr|en))/$', proj_views.set_language, name='setlang'),
    path('site_admin/', proj_views.site_admin, name='site_admin'),
    path('help/', proj_views.help_index, name='help_index'),
    path('help/<subject>/', proj_views.help, name='help'),

    path('jsi18n/', last_modified(lambda req, **kw: last_modified_date)(JavaScriptCatalog.as_view()),
        name='javascript_catalog'),

    path('policy/', pol_views.accept_policy, name='accept_policy'),
    path('', views.IndexView.as_view(), name='home'),

    path('search/', views.SearchView.as_view(), name='search'),
    path('search/export', views.SearchView.as_view(output='export'), name='search-export'),
    path('search/export-options', views.SearchView.as_view(output='export-options'), name='search-export-options'),
    path('search/add_criterion/<int:base_num>/',
        views.add_criterion, name='add_criterion'),
    path('search_images/', views.SearchView.as_view(form_class=ImageSearchForm, template_name='search/search_images.html'),
        name='search_img'),

    path('invent/', views.invent_list, name='inventories'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('invent/<int:parent_id>/new/<obj_code>/', views.ObjectCreateView.as_view(), name='object_create'),
    path('invent/<int:obj_id>/', views.object_detail, name='object_detail'),
    path('invent/<int:obj_id>/as_image/', views.object_image, name='object_image'),
    path('invent/<int:obj_id>/edit/', views.ObjectEditView.as_view(), name='object_edit'),
    path('invent/<int:obj_id>/editperms/', views.object_edit_perms, name='object_edit_perms'),
    path('invent/<int:obj_id>/delete/', views.object_delete, name='object_delete'),
    re_path(r'^invent/(?P<obj_id>\d+)/contents/(?P<otype>[-\w]+)?/?$',
        views.PaginatedObjectsView.as_view(), name='object_list'),
    path('invent/<int:obj_id>/reverse_refs/',
        views.PaginatedReverseObjectsView.as_view(), name='reverse_objects'),
    re_path(r'^invent/(?P<obj_id>\d+)/contents/(?P<otype>[-\w]+)/(?P<format>(table|geojson))/$',
        views.object_list_table, name='object_list_table'),
    re_path(r'^invent/by_uuid/(?P<uuid>[-\w]+)/(?P<format>(html|json|xml))?/?$',
        views.object_list_by_uuid, name='object_by_uuid'),
    path('invent/<int:obj_id>/import/', views.object_import, name='object_import'),
    path('attributes/', views.attributes, name='attributes'),
    # attribute name passed in GET
    path('attributes/vocab/', views.vocab_for_attribute, name='vocab_for_attribute'),

    re_path(r'^attributes_in_group/(?P<group_id>-?\d+)/$', views.attributes_in_group),

    path('<int:object_id>/value/new/<int:attr_id>/', views.add_value, name='add_value'),
    re_path(r'^(?P<object_id>\d+)/value/(?P<value_id>[\w\-]+)/edit/$', views.edit_value),
    path('<int:object_id>/value/del/', views.del_value, name='del_value'), # value id in POST
    # Image and file attachment editing
    path('<int:object_id>/photo/add/', views.add_photo, name="add_photo"),
    path('<int:object_id>/photo/<int:photo_id>/edit/', views.edit_photo),
    path('<int:object_id>/photo/del/', views.del_photo), # photo id in POST
    path('<int:object_id>/file/<int:file_id>/edit/', views.edit_file, name='edit_file'),
    path('<int:object_id>/file/del/', views.del_file), # file id in POST

    path('publications/', publications_views.PublicationsView.as_view(), name='publications'),
    path('press-corner/', publications_views.PressCornerView.as_view(), name='press_corner'),
]

if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

apps/invent/models.py
import datetime
import os
import re
import types
from collections import OrderedDict

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.contrib.staticfiles import finders
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import models
from django.db.models import Q, Value
from django.db.models.query import QuerySet
from django.db.models.signals import post_save
from django.template import Template
from django.urls import reverse
from django.utils.encoding import force_str
from django.utils.safestring import mark_safe, SafeData
from django.utils.translation import gettext, gettext_lazy as _

from sorl.thumbnail import ImageField
from mptt.managers import TreeManager
from mptt.models import MPTTModel

from invent.fields import UuidField
from invent.utils import truncate
from taxo.models import Taxon
from permission.models import Permission, PermissionMixin


# Monkey-patching User
class UserFunctions:
    def get_inventories(self):
        # Maybe return all root objects ?
        return self.baseobject_set.filter(obj_type__code="inventory").order_by('title')

    def is_siteadmin(self):
        """ Siteadmin can access 'user-oriented' site administration (not Django backend) """
        return self.is_superuser or \
               set([g.name for g in self.groups.all()]) & set(settings.SITE_ADMIN_GROUPS)

User.__bases__ += (UserFunctions,)


class DateValidator:
    code = 'invalid'
    valid_eurisco = r'^(?P<year>[12]\d\d\d)(----|(?P<month>[01]\d)(--|(?P<day>[0-3]\d)))?$' # 2004 or 19820529 or 200612-- or 2008----
    valid_iso     = r'^(?P<year>[12]\d\d\d)-(?P<month>[01]\d)-(?P<day>[0-3]\d)$' # 2008-03-12
    valid_ch_fr   = r'^((?P<day>[0-3]?\d)[\./])?(?P<month>[01]?\d)[\./](?P<year>[12]\d\d\d)$' # 21/12/2006 ou 04.07.2005

    def __call__(self, value):
        if isinstance(value, datetime.datetime):
            return value.date()
        if isinstance(value, datetime.date):
            return value
        if not isinstance(value, str):
            value = str(value)
        m = re.match(self.valid_eurisco, value) or re.match(self.valid_iso, value) or re.match(self.valid_ch_fr, value)
        if m is not None:
            year = m.group('year')
            month = m.group('month')
            day = m.group('day')

            year = int(year) if not year is None else datetime.date.today().year
            month = int(month) if month is not None else 1
            day = int(day) if day is not None else 1

            try:
                return datetime.date(year, month, day)
            except ValueError:
                pass

        raise ValidationError("The value '%s' is not valid for data type Date" % (value,), code=self.code)

date_validator = DateValidator()


class ObjectType(models.Model):
    """ Initial object types are filled by fixtures/initial_data.json """
    code        = models.SlugField(max_length=20)
    tname       = models.CharField(max_length=50, unique=True)
    icon        = models.ImageField(upload_to="icons", blank=True)
    searchable  = models.BooleanField(default=False,
        help_text="Available in 'Search in' select on search page")
    can_contain  = models.ManyToManyField('self', symmetrical=False, blank=True)

    class Meta:
        db_table = "object_type"

    def __str__(self):
        return self.tname

    @classmethod
    def as_choices(cls, only_searchable=False):
        """ Return a list of tuples of all object types suitable for a choice form widget """
        if only_searchable:
            return [(o.id, o.tname) for o in cls.objects.filter(searchable=True)]
        else:
            return [(o.id, o.tname) for o in cls.objects.all()]

    def has_taxonomy(self):
        return bool(self.attributeforobject_set.filter(attr_group__category='taxo').count())

    @property
    def possible_attributes(self):
        """ Return an attribute structure in the form (OrderedDict):
            {'group_name': [attributes,], ...}
        """
        if not hasattr(self, '_possible_attributes'):
            groups = [afo.attr_group for afo in self.attributeforobject_set.exclude(attr_group__isnull=True).select_related('attr_group')]
            self._possible_attributes =OrderedDict(zip([g.gname for g in groups], [[] for i in range(len(groups))]))
            for aig in AttributeInGroup.objects.filter(group__in=groups).order_by('position'):
                self._possible_attributes[aig.group.gname].append(aig.attribute)
            # Add non-grouped attributes
            for afo in self.attributeforobject_set.filter(attr_group__isnull=True).order_by('position'):
                self._possible_attributes.setdefault("Other Attributes", []).append(afo.attr)
        return self._possible_attributes

    def get_groups(self, categ_exclude=[], with_not_grouped=False):
        """ Return a list of all groups attached to this object type
            If with_not_grouped is True, a final fake group is added with all attributes for this ObjectType not in an attribute group
        """
        groups = [afo.attr_group for afo in self.attributeforobject_set.select_related('attr_group').all().order_by('position') if afo.attr_group and afo.attr_group.category not in categ_exclude]
        if with_not_grouped:
            groups.append(AttributeForObject.get_others_grouped(self))
        return groups

    def get_attributes(self):
        """ Returns a list of attributes valid for this object type """
        attr_list = []
        for afo in self.attributeforobject_set.all().order_by('position'):
            attr_list.extend(afo.get_attributes())
        for attr in attr_list:
            if attr.datatype == 'meta':
                # Add subattributes for metaattributes
                [attr_list.insert(attr_list.index(attr)+i+1, sub) for i, sub in enumerate(attr.subattributes.all())]
        return attr_list


class BaseObjectManager(TreeManager):
    def filter_writable_for_user(self, user):
        if user.is_superuser:
            return self.get_queryset()
        else:
            group_pks = [g.pk for g in user.groups.all()]
            return self.get_queryset().filter(
                Q(permissions__group__pk__in=group_pks, permissions__perm='rw') |
                Q(status="private", owner__pk=user.pk)
            )

STATUS_CHOICES = (
    ('private', _("Private")),
    ('public', _("Public")),
)
class BaseObject(MPTTModel, PermissionMixin):
    obj_type = models.ForeignKey(ObjectType, on_delete=models.CASCADE)
    uuid        = UuidField(unique=True, auto=True)
    title       = models.CharField(max_length=100, verbose_name=_("Title"))
    description = models.TextField(blank=True, null=True, verbose_name=_("Description"))
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)
    taxon = models.ForeignKey(Taxon, blank=True, null=True, on_delete=models.SET_NULL)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    status      = models.CharField(max_length=10, choices=STATUS_CHOICES, default='private')
    created     = models.DateTimeField(auto_now_add=True)
    modified    = models.DateTimeField(auto_now=True)
    weight      = models.SmallIntegerField(
        default=0, help_text="Higher numbers will make the item appear first in some lists")
    # Denormalized search content
    search_vector = SearchVectorField(null=True)
    photos      = GenericRelation('PhotoAttachment')
    files       = GenericRelation('FileAttachment')
    permissions = GenericRelation(Permission)
    
    objects = tree = BaseObjectManager()

    class Meta:
        db_table = "base_object"
        get_latest_by = "modified"

    def __str__(self):
        return self.title or str(self.pk)

    def __len__(self):
        return len(self.children.all())

    def __bool__(self):
        return True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._cached_values = None

    def get_absolute_url(self):
        return reverse('object_detail', args=[str(self.id)])
    
    # Functions inherited from mptt:
    #get_ancestors, get_children, get_descendants...
    #https://django-mptt.readthedocs.io/

    def _fill_cache(self):
        if self._cached_values is None:
            values = self.get_values()
            self._cached_values = {}
            for val in values:
                if val.attr.name in self._cached_values:
                    if isinstance(self._cached_values[val.attr.name], MetaValue):
                        self._cached_values[val.attr.name].append_value(val)
                    else:
                        meta = MetaValue(val.attr, val.obj, [self._cached_values[val.attr.name], val])
                        self._cached_values[val.attr.name] = meta
                else:
                    self._cached_values[val.attr.name] = val

    def index(self):
        self.search_vector = SearchVector('title') + SearchVector('description')
        for val in self.get_values():
            text = force_str(val.get_value())
            self.search_vector += SearchVector(Value(text, output_field=models.TextField()))
        if self.obj_type.code == 'image':
            self.search_vector += SearchVector(Value(self.parent.title, output_field=models.TextField()))

    def save(self, **kwargs):
        is_new = not bool(self.pk)
        if not is_new:
            self.index()
        super().save(**kwargs)
        if is_new:
            self.index()
            super().save(update_fields=['search_vector'])

    @classmethod
    def get_by_attr_value(cls, attr_name, value, limit_to=None):
        attr = Attribute.objects.get(name=attr_name)

templates/503.html
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Site Maintenance</title></head>

<body>
<div style="margin: 0 auto;">
<h1>This site is currently in maintenance mode</h1>

<p>Please come back in some minutes. Thanks for your undestanding.</p>
</div>

</body>
</html>

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Mycoscope: {% block title %}{{ title }}{% endblock %}</title>
  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'js/jquery.cookie.min.js' %}"></script>
  <script src="{% static 'js/jquery.hoverIntent.minified.js' %}"></script>
  <script src="{% static 'js/invent.js' %}"></script>
  <script>var static_url = "{{ STATIC_URL }}";</script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/taxo.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}" media="print" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/myco.css' %}"/>

  {% if form %}
  {{ form.media }}
  {{ form.js_init }}
  {% endif %}
  {% block extra_head %}{% endblock %}
</head>

<body>
    <div id="webHeaderDiv" style="display: flex;">
        <div style="flex-grow: 1;">
            <img src="{% static 'img/logo-agroscope.png' %}" style="margin-top: 0.7em; height: 60px;" alt="logo Confédération">
            <div id="webServiceNavigationDiv">
                <div class="search" style="margin-left: auto;">
                    <a href="{% url 'search' %}" class="header">{% trans "Search" %}</a> |
                    <a href="{% url 'publications' %}" class="header">{% trans "Publications" %}</a> |
                    <a href="{% url 'press_corner' %}" class="header">{% trans "Press corner" %}</a> |
                    {% if user.is_siteadmin %}
                      <a href="{% url 'site_admin' %}" class="header status-private">{% trans "Administration" %}</a> |&nbsp;&nbsp;
                    {% endif %}
                </div>
                {% include "login_div.html" %}
            </div>
        </div>
        <div>
            <img src="{% static 'img/logo.svg' %}" style="margin-top: 0.3em; width: 125px;" alt="Logo mycoscope">
        </div>
  </div>


<div class="content">
  {% block breadcrumb %}{% if breadcrumb %}
  <div id="breadcrumb">
    {% for level in breadcrumb %}
        {% if level.1 %}<a href="{{ level.1 }}">{% endif %}
        <span>{{ level.0 }}</span>{% if level.1 %}</a>{% endif %}
        {% if not forloop.last %} → {% endif %}
    {% endfor %}
  </div>{% endif %}
  {% endblock %}

  <div id="col_content">
    {% if messages %}
    <div id="site_message" class="message">
        {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span><br>
        {% endfor %}
    </div>
    {% endif %}

  {% block content %}
  {% endblock %}
  </div>
  
  {% block edition_content %}
  {% if user.is_authenticated %}
  <div id="col_func">
    {% block edit_widgets %}
    {% endblock %}
  </div>
  {% endif %}
  {% endblock %}

</div>

<div id="webFooter">
<div style="float:right; width: 46%;">
    <em>{% trans "Database implemented and updated by Nicole Lecoultre and Katia Gindro" %}</em>
</div>
copyright © 2025 <a href="https://www.agroscope.admin.ch/">Agroscope</a> &amp; <a href="https://www.2xlibre.net/">2xlibre.net Sàrl</a>
<br style='clear:both;'>
</div>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Home"%}{% endblock %}
{% block extra_head %}
  <style>
      h1 { font-size: 240%; border: none; }
      .welcome { font-size: 180%; font-weight: bold; padding-left: 5px; }
      #myco-logo { width: 75%; margin: 0 auto;}
      .head { font-size: 130%; }
      fieldset { padding-bottom: 1.5em; }
      .container { display: flex; justify-content: space-between; }
      .links { margin-left: 1em; }
      .links div { margin: 1em 0; border: 1px solid red; border-radius: 10px; padding: 0.7em;
        background-color: #fbe5d6; text-align: center; }
      #random_img img { max-width: 100%; margin: 1em 0; }
      .ac-head { font-style: italic; font-size: small; }
      .ac-results { margin-left: 1em; }
      .legend { text-align: center; font-style: italic; }
  </style>
  <script src="{% static 'js/autocomplete.js' %}"></script>
  <script>
    window.addEventListener('DOMContentLoaded', (event) => {
        window.autocomplete = new Autocomplete({
            form_selector: '.autocomplete',
            url: "{% url 'autocomplete' %}"
        });
        window.autocomplete.setup();
    });
  </script>
{% endblock %}

{% block edition_content %}{% endblock %}

{% block content %}

<p><span class="welcome">{% trans "Welcome on" %}</span><br>
<div id="myco-logo"><img src="{% static 'img/logo_text.svg' %}"></div>
</p>
<div style="display: flex; justify-content: space-between;">
    <div class="head text-center">{% trans "The database from Agroscope's Mycothèque" %}</div>
    <div class="text-center">
        {% trans "Mycothèque live:" %} <a href="https://www.youtube.com/watch?v=KLrYIt30GG8"><img src="{% static 'img/youtube-thumb.png' %}" style="vertical-align: middle;"></a>
    </div>
</div>

<fieldset class="text-center" style="margin-top: 0.5em;">
<form method="get" action="{% url 'search' %}" class="autocomplete">
    <p><b>{% trans "Search for a strain of mushroom" %}</b></p>
    <div>
        {{ form.text.errors }}
        {{ form.text }}
        <button>{% trans "Search" %}</button>
    </div>
    <div class="ac-head hidden">{% trans "Suggestions:" %}</div>
    <div class="ac-results"></div>
    <template id="resultTemplate">
        <div class="result-wrapper"><a href="" class="ac-result"></a></div>
    </template>
</form>
</fieldset>

<div class="container">
    <div id="random_img" class="text-center">
        <img src="{{ img_url }}" alt="image de {{ img_name }}">
        <div class="legend">{{ img_name }}</div>
    </div>
    {% if user.is_authenticated %}
    <div class="links">
        <div>
            <a href="{% url 'object_detail' 4062 %}">Mycothèque</a>
        </div>
        <div>
            <a href="{% url 'object_detail' 2407 %}">Herbier mycologique</a>
        </div>
        {% if perms.invent.add_baseobject %}
        <div>
            <a href="{% url 'object_create' 4062 "specimen" %}" id="create_link"><em>{% trans "New specimen…" %}</em></a>
        </div>
      {% endif %}
      </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/latest_block.html
{% load i18n %}
<div class="block">
  <h2>{% trans "Latest Inventories" %}</h2>
  <div class="block_content">
  <ul>
  {% for i in latest %}
  <li><a href="{{ i.get_absolute_url }}">{{ i.title }}</a></li>
  {% endfor %}
  </ul>
  <p><a href="{% url 'inventories' %}"><em>{% trans "More..." %}</em></a></p>
  </div>
</div>

templates/login_div.html
{% load i18n %}
<div class="login">
    {% if user.is_authenticated %}
      <span class="username"><a class="header" href="{% url 'profile' %}"><img src="{% static 'img/person.png' %}" class="icon" alt="person icon"> {{ user.username }}</a></span>&nbsp;&nbsp;
      <form style="display:inline;" method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <input type="image" src="{% static 'img/logout.png' %}" alt="{% trans 'Logout' %}" title="{% trans 'Logout' %}">
      </form>
    {% else %}
      <div><a href="{% url 'login' %}?next={{request.path}}">{% trans "Login" %}</a></div>
    {% endif %}
</div>